// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgUudhg6rmFbEL5MXCoTmdOMnV4U3KpDw',
    appId: '1:363892061106:web:8ea6f30c9527da5a91eaab',
    messagingSenderId: '363892061106',
    projectId: 'portfolio-37783',
    authDomain: 'portfolio-37783.firebaseapp.com',
    storageBucket: 'portfolio-37783.firebasestorage.app',
    measurementId: 'G-T8C7E7ZLQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi_TSJWB6KBTej0akPtUkVD1XLx9cMWwQ',
    appId: '1:363892061106:android:07b4fd6d21ff4ca091eaab',
    messagingSenderId: '363892061106',
    projectId: 'portfolio-37783',
    storageBucket: 'portfolio-37783.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC294Q4cOtZTdGN1aZltU4Q_H-tMzoIGzk',
    appId: '1:363892061106:ios:c7962cff1aee7cca91eaab',
    messagingSenderId: '363892061106',
    projectId: 'portfolio-37783',
    storageBucket: 'portfolio-37783.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC294Q4cOtZTdGN1aZltU4Q_H-tMzoIGzk',
    appId: '1:363892061106:ios:c7962cff1aee7cca91eaab',
    messagingSenderId: '363892061106',
    projectId: 'portfolio-37783',
    storageBucket: 'portfolio-37783.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgUudhg6rmFbEL5MXCoTmdOMnV4U3KpDw',
    appId: '1:363892061106:web:c252ab797ba2a38691eaab',
    messagingSenderId: '363892061106',
    projectId: 'portfolio-37783',
    authDomain: 'portfolio-37783.firebaseapp.com',
    storageBucket: 'portfolio-37783.firebasestorage.app',
    measurementId: 'G-SKV1DHCCWR',
  );
}
