// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5r238jHLdWuNYtcl1viFPTZuHymRGahw',
    appId: '1:372537212328:web:e6b277f5a80111dad5f19d',
    messagingSenderId: '372537212328',
    projectId: 'kunal-portfolio-94d4f',
    authDomain: 'kunal-portfolio-94d4f.firebaseapp.com',
    storageBucket: 'kunal-portfolio-94d4f.firebasestorage.app',
    measurementId: 'G-GGZMDHL4ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8WNradI44S9mbMFmdStBKd5dk7avsElU',
    appId: '1:372537212328:android:df57d4ee52fc7997d5f19d',
    messagingSenderId: '372537212328',
    projectId: 'kunal-portfolio-94d4f',
    storageBucket: 'kunal-portfolio-94d4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARMh4AVBVQRt9uON5rDn1TAEKJvd27nnc',
    appId: '1:372537212328:ios:964fb28100f35f34d5f19d',
    messagingSenderId: '372537212328',
    projectId: 'kunal-portfolio-94d4f',
    storageBucket: 'kunal-portfolio-94d4f.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARMh4AVBVQRt9uON5rDn1TAEKJvd27nnc',
    appId: '1:372537212328:ios:964fb28100f35f34d5f19d',
    messagingSenderId: '372537212328',
    projectId: 'kunal-portfolio-94d4f',
    storageBucket: 'kunal-portfolio-94d4f.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5r238jHLdWuNYtcl1viFPTZuHymRGahw',
    appId: '1:372537212328:web:ca6ca5160e85a442d5f19d',
    messagingSenderId: '372537212328',
    projectId: 'kunal-portfolio-94d4f',
    authDomain: 'kunal-portfolio-94d4f.firebaseapp.com',
    storageBucket: 'kunal-portfolio-94d4f.firebasestorage.app',
    measurementId: 'G-B1W2G9FBMK',
  );
}
